[package]
name = "vspreview-rs"
version = "0.1.0"
authors = ["quietvoid"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
glutin = "0.25.0"
piston_window = "0.113.0"
conrod_core = { git = "https://github.com/pistondevelopers/conrod", rev = "31a08c8" }
conrod_derive = "0.70.0"
conrod_piston = { git = "https://github.com/pistondevelopers/conrod", rev = "31a08c8" }
image = "0.23.10"
itertools = "0.9.0"
structopt = "0.3.18"
confy = "0.4.0"
serde_derive = "1.0.116"
serde = "1.0.116"
vapoursynth = { version = "0.3.0", features = ["vapoursynth-api-36", "vapoursynth-functions", "vsscript-api-32", "vsscript-functions"] }
