[package]
name = "vspreview-rs"
version = "0.1.0"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.58.1"
license = "GPL-3.0"

[dependencies]
vapoursynth = { git = "https://github.com/YaLTeR/vapoursynth-rs.git", features = ["vapoursynth-api-36", "vapoursynth-functions", "vsscript-api-32", "vsscript-functions"] }
clap = { version = "3.1.0", features = ["derive", "wrap_help"] }
eframe = { git = "https://github.com/emilk/egui.git", features = ["persistence"] }
image = { version = "0.24", default_features = false, features = ["png"] }
itertools = "0.10.3"
poll-promise = "0.1.0"
fast_image_resize = "0.7.0"

serde_derive = "1.0.133"
serde = "1.0.133"
num_enum = "0.5.6"
parking_lot = "0.12.0"

[profile.release]
debug = true
opt-level = 3
