[package]
name = "vspreview-rs"
version = "0.1.2"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.59.0"
license = "GPL-3.0"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive", "wrap_help"] }
eframe = { git = "https://github.com/emilk/egui.git", features = ["persistence"] }
fast_image_resize = "0.9.1"
image = { version = "0.24.2", default_features = false, features = ["png"] }
itertools = "0.10.3"
lcms2 = "5.4.1"
num_enum = "0.5.7"
parking_lot = "0.12.0"
poll-promise = "0.1.0"
rfd = "0.8.2"
serde_derive = "1.0.137"
serde = "1.0.137"
vapoursynth = { git = "https://github.com/YaLTeR/vapoursynth-rs.git", features = ["vapoursynth-api-36", "vapoursynth-functions", "vsscript-api-32", "vsscript-functions"] }

[[bin]]
name = "vspreview-rs"
path = "src/main.rs"

[profile.release]
opt-level = 3
strip = true
