[package]
name = "vspreview-rs"
version = "0.1.0"
authors = ["nark"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.109.0"
image = "0.23.5"
itertools = "0.9.0"
structopt = "0.3.15"
vapoursynth = { version = "0.3.0", features=["vapoursynth-api-36", "vapoursynth-functions", "vsscript-api-32", "vsscript-functions"] }