[package]
name = "vspreview-rs"
version = "0.1.0"
authors = ["quietvoid"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
glutin = "*"
piston_window = "0.109.0"
conrod_core = { git = "https://github.com/pistondevelopers/conrod", rev = "f448487" }
conrod_derive = "*"
conrod_piston = { git = "https://github.com/pistondevelopers/conrod", rev = "f448487" }
image = "0.23.9"
itertools = "0.9.0"
structopt = "0.3.17"
confy = "0.4.0"
serde_derive = "*"
serde = "*"
vapoursynth = { version = "0.3.0", features = ["vapoursynth-api-36", "vapoursynth-functions", "vsscript-api-32", "vsscript-functions"] }
