[package]
name = "vspreview-rs"
version = "0.1.0"
authors = ["quietvoid"]
edition = "2018"

[dependencies]
piston_window = "0.109.0"
image = "0.23.6"
itertools = "0.9.0"
structopt = "0.3.15"
vapoursynth = { version = "0.3.0", features = ["vapoursynth-api-36", "vapoursynth-functions", "vsscript-api-32", "vsscript-functions"] }
